sudo: false
language: android
android:
    components:
        # SDK version
        - android-23
        # Use the latest revision of Android SDK Tools
        - tools
        # Build tools version
        - build-tools-23.0.3
        # Android Support Library (appcompat)
        - extra-android-support
        # Android Support Repository
        - extra-android-m2repository
script:
    - ./gradlew test
deploy:
  - provider: script
    script: ./deploy-gh-pages.sh
    on:
      branch: master
  - provider: script
    script: ./deploy-bintray.sh
    on:
      tags: true

env:
  global:
  # GitHub
  - secure: "VCUWpAOMixNlwansoKUCHNVt5SKdZu+WEmgHN8u7fYO9HIPKciySyPipBasDy+oaXNKocXe1iLVAGRXue3b42cCLo0CMb3Tnoy/LuY6iv5KJzfKDaqHp1ggfKVgDBLfjwIfyNV54exAQLyTOMFS4lRneqRscuLE3ZfgTuH84EWs="
  # Bintray
  - secure: "FuB9QFkFCHfGOdtygHwekh/bBFIiLxKAhYBEYhic8VvZjtOkVW+Epz4uuywhioMAm8dFQUJP4HemnaKekhhO1HJXTQ2dw1da6Y0+7oRO41cTR/yexsls88G+DZ0ssr/ivkzkrF3QPGl7SV0ItYhgCx7whbELAWPboxYqDzEPVJY="
